table dim_month
	lineageTag: 77cb48c3-4da5-413c-9fe2-d1db76807835

	column month
		dataType: string
		lineageTag: d0c88bd6-0f8c-4bc4-ac8b-cca957597368
		summarizeBy: none
		sourceColumn: month
		sortByColumn: month_start

	column month_start
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 96616a8e-19d1-40a1-bf23-a99bb68dbe95
		summarizeBy: none
		sourceColumn: month_start

		annotation UnderlyingDateTimeDataType = Date

	partition dim_month = m
		mode: import
		source =
				let
				    // The programme calendar is derived from the dates it has to hold, never
				    // typed in. It used to be eighteen months from 2025-07, and the parallel
				    // runs start in 2025-05 - so three validation runs matched no month and sat
				    // in a blank row on every month-sliced visual, with the totals still right.
				    Plan = Table.PromoteHeaders(Csv.Document(File.Contents(DataPath & "\data\migration\migration_plan.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]), [PromoteAllScalars = true]),
				    Runs = Table.PromoteHeaders(Csv.Document(File.Contents(DataPath & "\data\migration\parallel_run_results.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]), [PromoteAllScalars = true]),
				    Dated = List.RemoveNulls(List.Transform(
				        List.Combine({Table.Column(Plan, "planned_cutover"), Table.Column(Plan, "actual_cutover"), Table.Column(Runs, "run_date")}),
				        each try Date.From(_) otherwise null)),
				    First = Date.StartOfMonth(List.Min(Dated)),
				    Last = Date.StartOfMonth(List.Max(Dated)),
				    Span = (Date.Year(Last) - Date.Year(First)) * 12 + Date.Month(Last) - Date.Month(First),
				    Months = List.Transform({0..Span}, each Date.AddMonths(First, _)),
				    ToTable = Table.FromList(Months, Splitter.SplitByNothing(), {"month_start"}),
				    Typed = Table.TransformColumnTypes(ToTable, {{"month_start", type date}}),
				    AddedLabel = Table.AddColumn(Typed, "month", each Date.ToText([month_start], "yyyy-MM"), type text),
				    Reordered = Table.ReorderColumns(AddedLabel, {"month", "month_start"})
				in
				    Reordered

